### ISSUE TITLE
cookie really buggy and freeze after few minute scrolling

### ISSUE THREAD

**Issue by binocry** [yendacoder/cookie#1]
spec android 11, ram 2gb. Qualcomm MSM8917 Snapdragon 425

maybe memory leak but idk

**Comment by yendacoder** [comment]
Is it happening consistently after some time, regardless of feed/specific posts you scroll by? Does it happen with all feed display modes?

**Comment by binocry** [comment]
> Is it happening consistently after some time, regardless of feed/specific posts you scroll by?

it happens consistently after few seconds I'm scrolling

> Does it happen with all feed display modes? 

try compact mode, still same: few scrolling, start stutter and then freeze or crash

**Comment by yendacoder** [comment]
For the sake of testing, can you please try the latest build?
https://github.com/yendacoder/cookie/releases/tag/v0.0.4-a
If id does not work out-of-the-box, try to disable image caching in settings and try again.

**Comment by binocry** [comment]
it's version 0.0.4

here's video for proof. i clear storage and cache on app settings and using default settings from app (only login). after few scrolling it's begin to struggle

https://streamable.com/w2uiq4

**Comment by yendacoder** [comment]
can you try the 0.0.4-a? And disable image cache in settings if it doesn't work right away

**Comment by binocry** [comment]
im try  0.0.4-a (don't realize that new version) and enable disable image cache. it's still same behavior. few scrolling and then start freezing. i can't using the app

**Comment by yendacoder** [comment]
Can you try again in the new build? But first go to the settings and disable "Inline full images"

https://github.com/yendacoder/cookie/releases/tag/v0.0.4-b

**Comment by binocry** [comment]
ok i clear data + cache and uninstall old version 
install v0.0.4-b, go to the settings and disable Inline full images and then login

seems promising so far! finally no freeze after few second scrolling homefeed!
maybe disable "Inline full images" should be default on settings. i dont see any different looks or behavior?

**Comment by yendacoder** [comment]
I'm closing this for now. The initial idea was to use the "original" full post image everywhere possible. Discuit API also provides several scaled down versions, but from what I've seen it often crops tall images in these thumbnails, which I personally dislike. For a high end phone (mine is 3 years old model with decent specs) loading full images in the feed is not a problem, but disabling this "Inline full images" feature can be beneficial also from the bandwidth perspective. When the toggle is off, the app tries to find the smallest thumbnail version that exceeds the size of the area the image is trying to fit.

Which way should be default is debatable, but I'm at least adding a clarification in the app about what that setting means.
